[package]
name = "tuke"
description = "A TUI software keyboard that drives a child process in a PTY"
version = "0.0.1"
edition = "2024"
authors = ["Takeru Ohta <phjgt308@gmail.com>"]
license = "MIT"
homepage = "https://github.com/sile/tuke"
repository = "https://github.com/sile/tuke"
readme = "README.md"

[dependencies]
libc = "0.2"
noargs = "0.4.3"
nojson = "0.3.15"
tuinix = "0.7.0"
termnix = "0.3"
